language: android
android:
  components:
    - build-tools-21.1.1
    - android-23
    - extra-android-m2repository
    - extra-android-support
script:  
  - ./gradlew assembleRelease

before_install:
     - chmod +x gradlew