language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-26
    - extra-android-m2repository
    - extra-android-support
before_install:
     - chmod +x gradlew
     - mkdir -p $ANDROID_HOME/licenses
     - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
     - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_HOME/licenses/android-sdk-license
install:
  - echo y | sdkmanager "ndk-bundle"
  - echo y | sdkmanager "cmake;3.6.4111459"
  - echo y | sdkmanager "lldb;3.1"
script:
  - ./gradlew assembleDebug
