language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.0
    - android-25
    - extra-android-m2repository
    - extra-android-support
script:
  - ./accept
  - ./gradlew assembleDebug

before_install:
     - chmod +x gradlew
     - chmod +x accpet
